#SSL Termination Secret:

apiVersion: v1
kind: Secret
metadata:
  name: ssl-secret
  namespace: example-namespace
data:
  tls.crt: <base64-encoded-cert>
  tls.key: <base64-encoded-key>
type: kubernetes.io/tls

#Environment Variables Secret:

apiVersion: v1
kind: Secret
metadata:
  name: app-env-secret
  namespace: example-namespace
data:
  USERNAME: <base64-encoded-username>
  PASSWORD: <base64-encoded-password>
